name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Changez cela si vous utilisez une autre branche pour déployer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        npm install
        npm run prod

    - name: Upload to cPanel
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.SERVEUR_FTP}} 
        username: ${{ secrets.NOM_D_UTILISATEUR_FTP}} 
        password: ${{ secrets.FTP_PASSWORD}} 
        server-dir: /
